from tkinter import *
from tkinter import messagebox
root=Tk()
root.title('MENU')
root.geometry("600x400")
root.configure(bg="beige")
t=Text(root, width=40, height= 1, font=("Times", "30", "bold"), fg="white", bg="blue", wrap=WORD)
t.insert(END,"EXPENSE TRACKER")
t.pack(side=TOP)
f3=Frame(root, bg="black",padx=80,pady=20)
f3.pack()

b1=Button(f3,text='DASHBOARD',width=23,height=3, bg="green1", activebackground="azure")
b2=Button(f3,text='ADD INCOME/EXPENSE',width=23,height=3, bg="orange", activebackground="azure")
b3=Button(f3,text='STATISTICS',width=23,height=3, bg="orange", activebackground="azure")
b4=Button(f3,text='UPDATE INCOME/EXPENSE',width=23,height=3, bg="green1", activebackground="azure")
b5=Button(f3,text='CALENDAR',width=23,height=3, bg="green1", activebackground="azure")
b6=Button(f3,text='DELETE INCOME/EXPENSE',width=23,height=3, bg="orange", activebackground="azure")
b7=Button(f3,text='NOTES',width=23,height=3, bg="orange", activebackground="azure")
b8=Button(f3,text='ACC INFO',width=23,height=3, bg="green1", activebackground="azure")
b9=Button(f3,text='FAQs',width=23,height=3, bg="dodgerblue", activebackground="yellow")
b10=Button(f3,text='LOGOUT!',width=23,height=3, bg="red", activebackground="yellow")

b1.grid(row=0,column=0,pady=5)
b2.grid(row=0,column=1,pady=5,padx=20)
b3.grid(row=2,column=0,pady=5)
b4.grid(row=2,column=1,pady=5)
b5.grid(row=4,column=0,pady=5)
b5.grid(row=4,column=0,pady=5)
b6.grid(row=4,column=1,pady=5)
b7.grid(row=6,column=0,pady=5)
b8.grid(row=6,column=1,pady=5)
b9.grid(row=8,column=0,pady=5)
b10.grid(row=8,column=1,pady=5)
root.mainloop()